package at.tuwien.monitoring.server.db.dao;

import java.util.Collections;
import java.util.List;

import org.apache.log4j.Logger;
import org.sql2o.Connection;
import org.sql2o.Sql2oException;

import at.tuwien.monitoring.server.db.DbConnection;
import at.tuwien.monitoring.server.db.dto.ViolationDTO;

public class ViolationDAO {

	private final static Logger logger = Logger.getLogger(ViolationDAO.class);

	private static final String SQL_CREATE_TABLE = "CREATE TABLE IF NOT EXISTS violation("
			+ "id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, "
			+ "source_ip_address VARCHAR(32) NOT NULL, "
			+ "service_name VARCHAR(1024) NOT NULL, "
			+ "violation_type VARCHAR(255) NOT NULL, "
			+ "monitored_value FLOAT NOT NULL, "
			+ "required_desc VARCHAR(255) NOT NULL,"
			+ "violation_timestamp TIMESTAMP NOT NULL"
			+ ");";

	private static final String SQL_SELECT_ALL = "SELECT id, source_ip_address sourceIpAddress, service_name servicename, "
			+ "violation_type violationType, monitored_value monitoredValue, "
			+ "required_desc requiredDesc, violation_timestamp violationTimestamp FROM violation";

	private static final String SQL_INSERT = "INSERT INTO violation(source_ip_address, service_name, "
			+ "violation_type, monitored_value, required_desc, violation_timestamp) "
			+ "values (:sourceIpAddress, :serviceName, :violationType, :monitoredValue, :requiredDesc, :violationTimestamp)";

	public void ceateTable() {
		try (Connection con = DbConnection.INSTANCE.getConn().open()) {
			con.createQuery(SQL_CREATE_TABLE).executeUpdate();
			logger.info("Database table `violation` created.");
		} catch (Sql2oException e) {
			e.printStackTrace();
			logger.error("Error creating table violation.");
		}
	}

	public List<ViolationDTO> findAll() {
		try (Connection con = DbConnection.INSTANCE.getConn().open()) {
			return con.createQuery(SQL_SELECT_ALL).executeAndFetch(ViolationDTO.class);
		} catch (Sql2oException e) {
			logger.error("Error querying violations from DB.");
			return Collections.emptyList();
		}
	}

	public List<ViolationDTO> findByIp(String ipAddress) {
		String query = SQL_SELECT_ALL + " WHERE source_ip_address='" + ipAddress + "'";
		try (Connection con = DbConnection.INSTANCE.getConn().open()) {
			return con.createQuery(query).executeAndFetch(ViolationDTO.class);
		} catch (Sql2oException e) {
			logger.error("Error querying violations from DB.");
			return Collections.emptyList();
		}
	}

	public void insert(ViolationDTO violationDTO) {
		try (Connection con = DbConnection.INSTANCE.getConn().open()) {
			con.createQuery(SQL_INSERT).bind(violationDTO).executeUpdate();
		} catch (Sql2oException e) {
			e.printStackTrace();
			logger.error("Error inserting violation into DB.");
		}
	}
}